[package]
name = "blueshift_vault"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.10.1"
pinocchio-system = "0.5.0"
solana-address = { version = "2.1.0", features = ["curve25519"] }

[lib]
crate-type = ["lib", "cdylib"]
