[package]
name = "blueshift_escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
pinocchio = "0.8.4"
pinocchio-associated-token-account = "0.3.0"
pinocchio-system = "0.5.0"
pinocchio-token = "0.5.0"


[lib]
crate-type = ["lib", "cdylib"]


